-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.employee_skills
    RENAME id TO score;

ALTER TABLE public.employee_skills
    ALTER COLUMN score TYPE integer;
ALTER TABLE IF EXISTS public.employee_skills
    ALTER COLUMN score SET DEFAULT 0;

ALTER TABLE IF EXISTS public.employee_skills
    ALTER COLUMN score DROP IDENTITY;
