-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.employee_skills
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    employee_id bigint NOT NULL,
    skill_id bigint NOT NULL,
    score integer NOT NULL,
    CONSTRAINT employee_skills_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.employee_skills
    OWNER to postgres;

GRANT ALL ON TABLE public.employee_skills TO anon;

GRANT ALL ON TABLE public.employee_skills TO authenticated;

GRANT ALL ON TABLE public.employee_skills TO postgres;

GRANT ALL ON TABLE public.employee_skills TO service_role;
